name: Compiler workflow for caddy2.x
on:
  workflow_dispatch:
    inputs:
      caddyv:
        description: 'caddy version'
        default: 'v2.9.1'
        required: false
        type: string
      xcaddyv:
        description: 'xcaddy version'
        default: '0.4.4'
        required: false
        type: string

jobs:
  compile_release:
    runs-on: ubuntu-latest
    steps:
    - name: download xcaddy
      run: |
        wget https://github.com/caddyserver/xcaddy/releases/download/v${{ inputs.xcaddyv }}/xcaddy_${{ inputs.xcaddyv }}_linux_amd64.tar.gz
        tar -xzf xcaddy_${{ inputs.xcaddyv }}_linux_amd64.tar.gz
        ls -lh
      working-directory: /tmp
    - name: compile caddy
      run: |
        GOARCH=amd64 GOOS=linux ./xcaddy build ${{ inputs.caddyv }} --with github.com/git001/caddyv2-upload --output caddy-amd64
        GOARCH=arm64 GOOS=linux ./xcaddy build ${{ inputs.caddyv }} --with github.com/git001/caddyv2-upload --output caddy-arm64
        ls -lh
      working-directory: /tmp
    - name: release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          /tmp/caddy-amd64
          /tmp/caddy-arm64
        tag_name: caddy-${{ inputs.caddyv }}_linux